--2, SOAL B
--Create DDL 
/*
2440116031 - Nadzla Andrita Intan Ghayatrie 
2440109556 - Wanda Safira 
2440110886 - Vincent
*/

CREATE DATABASE cArDorm
GO
USE cArDorm
GO

CREATE TABLE MsStaff(
	StaffID CHAR(5) PRIMARY KEY CHECK(StaffID LIKE 'ST[0-9][0-9][0-9]'),
	StaffName VARCHAR(30) NOT NULL,
	StaffGender VARCHAR(6) CHECK(StaffGender LIKE 'Female' OR StaffGender LIKE 'Male') NOT NULL,
	StaffEmail VARCHAR(30) CHECK(StaffEmail LIKE '%@gmail.com' OR StaffEmail LIKE '%@yahoo.com') NOT NULL,
	StaffPhoneNumber VARCHAR(13) NOT NULL,
	StaffAddress VARCHAR(30) NOT NULL,
	StaffSalary INT CHECK(StaffSalary BETWEEN 5000000 AND 10000000) NOT NULL
)

CREATE TABLE MsCustomer(
	CustomerID CHAR(5) PRIMARY KEY CHECK(CustomerID LIKE 'CU[0-9][0-9][0-9]') NOT NULL,
	CustomerName VARCHAR(30) NOT NULL,
	CustomerGender VARCHAR(6) CHECK(CustomerGender LIKE 'Female' OR CustomerGender LIKE 'Male') NOT NULL,
	CustomerAddress VARCHAR(30) NOT NULL,
	CustomerPhoneNumber VARCHAR(13) NOT NULL,
	CustomerEmail VARCHAR(30) CHECK(CustomerEmail LIKE '%@gmail.com' OR CustomerEmail LIKE '%@yahoo.com') NOT NULL
)

CREATE TABLE MsVendor(
	VendorID CHAR(5) PRIMARY KEY CHECK(VendorID LIKE 'VE[0-9][0-9][0-9]') NOT NULL,
	VendorName VARCHAR(30) NOT NULL,
	VendorEmail VARCHAR(30) CHECK(VendorEmail LIKE '%@gmail.com' OR VendorEmail LIKE '%@yahoo.com') NOT NULL,
	VendorPhoneNumber VARCHAR(13) NOT NULL,
	VendorAddress VARCHAR(30) NOT NULL
)

CREATE TABLE MsBrand(
	BrandID CHAR(5) PRIMARY KEY CHECK(BrandID LIKE 'CB[0-9][0-9][0-9]') NOT NULL,
	BrandName VARCHAR(30) NOT NULL
)

CREATE TABLE MsCar(
	CarID CHAR(5) PRIMARY KEY CHECK(CarID LIKE 'CA[0-9][0-9][0-9]') NOT NULL,
	BrandID CHAR(5) FOREIGN KEY REFERENCES MsBrand(BrandID) ON UPDATE CASCADE ON DELETE CASCADE,
	CarName VARCHAR(30) NOT NULL,
	CarPrice INT NOT NULL,
	CarStock INT NOT NULL
)

CREATE TABLE MsTransaction(
	TransactionID CHAR(5) PRIMARY KEY CHECK(TransactionID LIKE 'TR[0-9][0-9][0-9]') NOT NULL,
	CustomerID CHAR(5) FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	CarSold CHAR(5) FOREIGN KEY REFERENCES MsCar(CarID) ON UPDATE CASCADE ON DELETE CASCADE,
	TransactionDate DATE NOT NULL,
	Quantity INT NOT NULL
)

CREATE TABLE MsPurchase(
	PurchaseID CHAR(5) PRIMARY KEY CHECK(PurchaseID LIKE 'PU[0-9][0-9][0-9]') NOT NULL,
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	VendorID CHAR(5) FOREIGN KEY REFERENCES MsVendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE,
	CarPurchased CHAR(5) FOREIGN KEY REFERENCES MsCar(CarID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseDate DATE NOT NULL,
	QuantityPurchase INT NOT NULL
)

